### ISSUE TITLE
<leader>asdf should not be mapped

### ISSUE THREAD

**Issue by cormacrelf** [tjdevries/lsp_extensions.nvim#10]
```
:map ,a
n  ,asdf       * :lua require('plenary.reload').reload_module('lsp_extensions'); require('lsp_extensions').test()<CR>
        Last set from ~/.dotfiles/vim/vim.symlink/plugged/lsp_extensions.nvim/plugin/lsp_extensions.vim line 1
```

This is, I presume, something for developing lsp_extensions. But it interferes with user defined mappings, e.g. `:nmap <leader>a` now takes a few seconds to activate as it waits to see if you go on to type `sdf`. So put it in your own vimrc or something.

**Comment by PatOConnor43** [comment]
Hi @cormacrelf, thanks for the report. I think we can probably get rid of that mapping. I put up a PR to remove it but I can't merge it. Hopefully maintainers can merge it in the next couple days.
