### ISSUE TITLE
rust-analyzer: Add better support for `TypeHint`s and `ParameterHint`s

### ISSUE THREAD

**Issue by PatOConnor43** [tjdevries/lsp_extensions.nvim#14]
The current rust inlay-hints implementation puts everything at the end of the line when the intended behavior of `Type` and `Parameter` hints is to be interspersed in the line. We should be able to draw these hints more closely to this.
![image](https://user-images.githubusercontent.com/6657525/97119737-61d01400-16cf-11eb-9d7d-1abd522abd89.png)
Where TypeHints go after variable declarations and ParameterHints are paired with their variables.

Related PRs:
https://github.com/nvim-lua/lsp_extensions.nvim/pull/13
https://github.com/nvim-lua/lsp_extensions.nvim/pull/9

**Comment by mvforell** [comment]
To my knowledge it is currently not possible to display the hints in other positions than at the end of the line. The hints are added as virtual text which can only be placed after any other text in the line (see the [documentation](https://neovim.io/doc/user/api.html#nvim_buf_set_virtual_text())).

**Comment by PatOConnor43** [comment]
I just read that in the docs too :sweat_smile: Well, this may not work how I want it to then :grimacing:

**Comment by mvforell** [comment]
I guess we'll have to wait until NeoVim supports virtual text in arbitrary positions...

**Comment by PatOConnor43** [comment]
This PR seems very related as well https://github.com/neovim/neovim/pull/9496

**Comment by PatOConnor43** [comment]
It also seems like coc-rust-analyzer also only supports `ChainingHint`s for this reason.
https://github.com/fannheyward/coc-rust-analyzer/issues/177#issuecomment-619312150

**Comment by rockerBOO** [comment]
https://github.com/nvim-lua/lsp_extensions.nvim/pull/19

This adds support for setting your own options of the hints you want. 

```
require'lsp_extensions'.inlay_hints{ enabled = {"ChainingHint", "TypeHint", "ParameterHint"} } 
```

**Comment by PatOConnor43** [comment]
That should be fine. I'll close this.

**Comment by univerz** [comment]
this workaround looks useful https://github.com/fannheyward/coc-rust-analyzer/issues/394#issuecomment-743468861
