### ISSUE TITLE
Error in inlay_hints.lua: ipairs expected table, got number

### ISSUE THREAD

**Issue by LeonGr** [tjdevries/lsp_extensions.nvim#15]
After updating to the latest neovim nightly version (NVIM v0.5.0-781-ga22fe09b9, however the error still existed when I tried to downgrade) when I open a file and `inlay_hints()` is called I get the following error:
```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...d/lsp_extensions.nvim/lua/lsp_extensions/inlay_hints.lua:65: bad argument #1 to 'ipairs' (table expected, got number)
```
This seems to be caused by `result` being equal to 0 and `not 0 == false` in Lua, so it ignores the `if not result` guard in line 54. Changing this line into `if not result or result == 0` works as a workaround.

**Comment by glepnir** [comment]
should be fixed.
