### ISSUE TITLE
On startup of nvim, broken with new versions of neovim nightly

### ISSUE THREAD

**Issue by marioidival** [tjdevries/lsp_extensions.nvim#17]
Broken with new versions of neovim nightly

```BufWinEnter Autocommands for "*": E5108: Error executing lua ...d/lsp_extensions.nvim/lua/lsp_extensions/inlay_hints.lua:65: bad argument #1 to 'ipairs' (table expected, got number)```

**Comment by glepnir** [comment]
@marioidival  can your test the new commit?

**Comment by marioidival** [comment]
Hello @glepnir , this problem is done, but now I have this:
```
BufWinEnter Autocommands for "*":
E5108: Error executing lua shared.lua:199: Expected table, got number
```

**Comment by marioidival** [comment]
My init.vim has this line related.

```
autocmd BufEnter,BufWinEnter,TabEnter * :lua require'lsp_extensions'.inlay_hints{}
```

**Comment by glepnir** [comment]
@marioidival  hey this only work for rust. so your autocmd is wrong . use `*.rs`

**Comment by marioidival** [comment]
@glepnir I know, but this error happens also on rust files

```
BufWinEnter Autocommands for "*.rs":
E5108: Error executing lua shared.lua:199: Expected table, got number```

**Comment by marioidival** [comment]
@tjdevries closed because has solved?
