### ISSUE TITLE
Support typescript inlay hints? 

### ISSUE THREAD

**Issue by entropitor** [tjdevries/lsp_extensions.nvim#28]
Typescript added inlay hints in the latest version: https://github.com/microsoft/TypeScript/pull/42089

And it seems this is how they added it to vscode: https://github.com/microsoft/vscode/pull/113412/files, it would be nice if we could add it to neovim as well and given this plugin already seems support the same for rust...

**Comment by rockerBOO** [comment]
See https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/issues/40 which may be better suited for supporting this.
